### ISSUE TITLE
Fix a bug where discord node server randomly crashes.

### ISSUE THREAD

**Issue by nmaier95** [samsour/legends-of-discordia#8]
We should go back in vcs history and check if this is a bug with the library itself or if we messed something up.

**Comment by nmaier95** [comment]
I was not able to reproduce this any longer. Maybe it had something to do with the discord authentication service or they did a deployment or similar... 

Please verify and feel free to close the issue.

**Comment by samsour** [comment]
Hi @nmaier95, the error seems to be caused by certain node versions. Node version 14.17.0 and 15.14.0 seem to work fine. But it still occurs with version 16.x and somehow on every Node instance that is running encapsulated in a docker container. So my docker containers are not working at all.

**Comment by nmaier95** [comment]
Fixed with #11
